//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_EF_GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoteXDevolucion
    {
        public int ID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> ID_Lote { get; set; }
        public Nullable<int> ID_Devolucion { get; set; }
        public Nullable<int> ID_EstadoLote { get; set; }
    
        public virtual Devolucion Devolucion { get; set; }
        public virtual EstadoLote EstadoLote { get; set; }
        public virtual Lote Lote { get; set; }
    }
}
