//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_EF_GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoteXEnvioXVenta
    {
        public int ID { get; set; }
        public Nullable<int> ID_LoteXEnvio { get; set; }
        public Nullable<int> ID_Venta { get; set; }
    
        public virtual LoteXEnvio LoteXEnvio { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
