//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_EF_GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lote()
        {
            this.LoteXDevolucion = new HashSet<LoteXDevolucion>();
            this.LoteXEnvio = new HashSet<LoteXEnvio>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CantidadInicial { get; set; }
        public Nullable<int> CantidadActual { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> ID_Producto { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoteXDevolucion> LoteXDevolucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoteXEnvio> LoteXEnvio { get; set; }
    }
}
