//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_EF_GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoteXEnvio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoteXEnvio()
        {
            this.LoteXEnvioXVenta = new HashSet<LoteXEnvioXVenta>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CantidadInicial { get; set; }
        public Nullable<int> CantidadRecibido { get; set; }
        public Nullable<int> CantidadActual { get; set; }
        public Nullable<int> ID_EstadoLote { get; set; }
        public Nullable<int> ID_Lote { get; set; }
        public Nullable<int> ID_Envio { get; set; }
    
        public virtual Envio Envio { get; set; }
        public virtual EstadoLote EstadoLote { get; set; }
        public virtual Lote Lote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoteXEnvioXVenta> LoteXEnvioXVenta { get; set; }
    }
}
