//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_EF_GestionStock
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionStock_v1Entities : DbContext
    {
        public GestionStock_v1Entities()
            : base("name=GestionStock_v1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Devolucion> Devolucion { get; set; }
        public virtual DbSet<Envio> Envio { get; set; }
        public virtual DbSet<EstadoLote> EstadoLote { get; set; }
        public virtual DbSet<Lote> Lote { get; set; }
        public virtual DbSet<LoteXDevolucion> LoteXDevolucion { get; set; }
        public virtual DbSet<LoteXEnvio> LoteXEnvio { get; set; }
        public virtual DbSet<LoteXEnvioXVenta> LoteXEnvioXVenta { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
    }
}
